# calc-server-square-controller.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: calc-server-square-svc
  name: calc-server-square-svc
spec:
  replicas: 5
  selector:
    matchLabels:
      run: calc-server-square-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: calc-server-square-svc
    spec:
      containers:
      - image: gcr.io/viki-stg/calc_server_square:v2
        imagePullPolicy: IfNotPresent
        name: calc-server-square-svc
        ports:
        - containerPort: 8080
          name: http-server
      dnsPolicy:  ClusterFirst
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: calc-server-square-svc
  name: calc-server-square-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: calc-server-square-svc
  type: ClusterIP
---
# calc-server-add-controller.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: calc-server-add-svc
  name: calc-server-add-svc
spec:
  replicas: 5
  selector:
    matchLabels:
      run: calc-server-add-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: calc-server-add-svc
    spec:
      containers:
      - image: gcr.io/viki-stg/calc_server_add:v2
        imagePullPolicy: IfNotPresent
        name: calc-server-add-svc
        ports:
        - containerPort: 8081
          name: http-server
      dnsPolicy:  ClusterFirst
      restartPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: calc-server-add-svc
  name: calc-server-add-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: calc-server-add-svc
  type: ClusterIP
---
# calc-server-sqrt-controller.yml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: calc-server-sqrt-svc
  name: calc-server-sqrt-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      run: calc-server-sqrt-svc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: calc-server-sqrt-svc
    spec:
      containers:
      - image: gcr.io/viki-stg/calc_server_sqrt:v2
        imagePullPolicy: IfNotPresent
        name: calc-server-sqrt-svc
        ports:
        - containerPort: 8082
          name: http-server
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: calc-server-sqrt-svc
  name: calc-server-sqrt-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    run: calc-server-sqrt-svc
  loadBalancerSourceRanges:
  - 0.0.0.0/0
